#!/bin/bash

apt update

apt install mysql-server
systemctl start mysql.service
apt install nodejs -y
apt install npm -y
npm install

cp /home/ubuntu/crudapp/crud.service /etc/systemd/system/crud.service

systemctl start crud.service
systemctl enable crud.service
